name: Unit Tests

on:
    push:
        branches: [ main ]
    pull_request: ~
    schedule:
        # Do not make it the first of the month and/or midnight since it is a very busy time
        - cron: "* 10 6 * *"
    release:
        types: [ created ]

# See https://stackoverflow.com/a/72408109
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        name: Unit-Tests (PHP ${{ matrix.php.version }}, ${{ matrix.php.dependency }}, ${{ matrix.tools }}) - PHAR ${{ matrix.phar-readonly && 'readonly' || 'writeable' }}${{ matrix.label }}
        strategy:
            fail-fast: false
            matrix:
                php:
                    # Locked is only for the current configured platform
                    -   version: '8.3'
                        dependencies: 'locked'
                        composer-options: ''
                    # Other PHP versions
                    -   version: '8.3'
                        dependencies: 'lowest'
                        composer-options: ''
                    -   version: '8.3'
                        dependency: 'highest'
                        composer-options: ''
                    # Upcoming PHP version
                    -   version: '8.4'
                        dependency: 'highest'
                        composer-options: '--ignore-platform-req=php+'
                tools:
                    - 'composer'
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php.version }}
                    ini-values: display_errors=On, error_reporting=-1
                    tools: ${{ matrix.tools }}
                    coverage: none
                    extensions: none

            -   name: Remove the configured platform on non-locked dependencies
                if: ${{ matrix.php.dependency != 'locked' }}
                run: composer config platform.php --unset

            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v3
                with:
                    dependency-versions: ${{ matrix.php.dependency }}
                    composer-options: ${{ matrix.php.composer-options }}

            -   name: Ensure that the make target is up to date
                run: make vendor_install

            -   run: make test


    # This is a "trick", a meta task which does not change, and we can use in
    # the protected branch rules as opposed to the tests one above which
    # may change regularly.
    validate-tests:
        name: Unit tests status
        runs-on: ubuntu-latest
        needs:
            - unit-tests
        if: always()
        steps:
            - name: Successful run
              if: ${{ !(contains(needs.*.result, 'failure')) }}
              run: exit 0

            - name: Failing run
              if: ${{ contains(needs.*.result, 'failure') }}
              run: exit 1
